export const FETCH_MARKEET_REQUEST = 'FETCH_MARKEET_REQUEST';
export const FETCH_MARKEET_SUCCESS = 'FETCH_MARKEET_SUCCESS';
export const FETCH_MARKEET_FAILURE = 'FETCH_MARKEET_FAILURE';
export const CHANGE_TAB = 'CHANGE_TAB';